# @package _global_
model:
  type: mnistCNN
  classname: MnistCNN
  pretraining:
    weights:
    load_layers: [conv1.weight, conv1.bias, conv2.weight, conv2.bias]
    freeze_layers:
  args: {}  # args to the specific class