defaults:
  - model: ???
  - algo: ???
  - dataset: ???
  - logger: wandb
  - _self_

n_round: 10000
device: ['cuda:0']

seed: 2021
output_suffix: ""
do_train: True
checkpoint_path:
sub: ""
exp_name: ${algo.type}_${dataset.type}_${model.type}_alpha${algo.params.common.alpha}_K${algo.params.common.K}_C${algo.params.common.C}${sub}
debug: False
root: ${oc.env:PWD}
savedir: ${oc.env:PWD}/output/${exp_name}/seed_${seed}

hydra:
  run:
    dir: ${oc.env:PWD}/output/${exp_name}/seed_${seed}
  sweep:
    # Output directory for sweep runs
    dir: ${oc.env:PWD}/output/${exp_name}
    # Output sub directory for sweep runs.
    subdir: seed_${seed}
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}${output_suffix}.log