# @package _global_
defaults:
  - fedavg

algo:
  type: feddyn
  params:
    alpha: ???
    center_server:
      classname: FedDynCenterServer
      args:
        num_clients: ${algo.params.common.K}
        alpha: ${algo.params.alpha}
    client:
      classname: FedDynClient
      args:
        alpha: ${algo.params.alpha}