# @package _global_
defaults:
  - fedavg

algo:
  type: ghb
  classname: FedAvg
  params:
    type: ghbm
    variant: standard
    center_server:
      classname: GHBMCenterServer
      args:
        tau: ???
    client:
      classname: GHBMClient
      args:
        beta: 0.9
        nesterov: False

