# @package _global_
defaults:
  - fedavg

algo:
  type: naivehbm
  classname: FedAvg
  params:
    mode: 'standard'
    client:
      classname: LocalGHBMClient
      args:
        C: ${algo.params.common.C}
        beta: 0.9
        variant: standard
        nesterov: False
