# @package _global_
dataset:
  type: cifar100
  classname: CIFAR100
  args:
    root: "./datasets"
    download: True
  data_splitter:
    classname: DirichletDataSplitter
    args:
      alpha: ${algo.params.common.alpha}
      rebalance: True
      max_iter_rebalance: 100
  num_exemplars: 1000 # exemplars to extract from test data